import re

class ResponseParser:
    """Parses raw text responses from the LLM and extracts clean code blocks."""

    def extract_code(self, response_text: str) -> str:
        """Find and extract the code block from the markdown response.
        
        Args:
            response_text: Raw string generated by the LLM.
            
        Returns:
            The extracted source code, or the original response if no code block was found.
        """
        if not response_text:
            return ""

        # Pattern to capture contents of a markdown code block, optionally ignoring language tag
        # e.g., ```python\nCodeHere\n```
        code_block_pattern = re.compile(r'```(?:[a-zA-Z0-9#+-]+)?\n(.*?)\n```', re.DOTALL)
        
        match = code_block_pattern.search(response_text)
        if match:
            return match.group(1).strip()

        # Fallback: if there are no backticks but backticks exist in some other form
        # E.g., just starts with standard comments
        cleaned_text = response_text.strip()
        if cleaned_text.startswith("```"):
            # Strip triple backticks if the regex missed it
            lines = cleaned_text.splitlines()
            if lines[0].startswith("```"):
                lines = lines[1:]
            if lines and lines[-1].startswith("```"):
                lines = lines[:-1]
            return "\n".join(lines).strip()

        return response_text.strip()
